### ISSUE TITLE
Disable rtsp server automatic deactivation

### ISSUE THREAD

**Issue by sebasptsch** [tsightler/ring-mqtt#282]
**Describe the problem**  
At the moment I'm trying to integrate my Ring camera with frigate but every time I try and connect using Frigate Vlc or the WebRTC addon in HA it times out before the stream has been fully started. And because it times out the request fails resulting in an infinite loop of trying to start the stream -> timing out -> stream starting -> stream deactivating -> trying to start the stream again. 

**Describe your environment**  
Ring-MQTT docker container.

**Describe any steps you've taken to attempt to resolve the problem**  
I've tried starting the stream using VLC but it also times out before the stream is started.

**Debug Logs**  
<details>
  <summary>Debug Logs</summary>
  <pre>

2021-10-17T03:18:49.025Z ring-mqtt [Front Door] Establishing connection to live stream

2021-10-17T03:18:49.068Z ring-rtsp [Front Door] Live stream is activating

    at TLSSocket.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/lib/api/sip.js:557:38)

    at TLSSocket.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/lib/api/sip.js:557:38)

2021-10-17T03:18:51.054Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"active"}

2021-10-17T03:18:51.093Z ring-rtsp [Front Door] Live stream is active!

2021-10-17T03:18:58.971Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43106] opened

2021-10-17T03:18:58.987Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command stopped

2021-10-17T03:18:58.987Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43106] ERR: source of path 'e04f434a5122_live' has timed out

2021-10-17T03:18:58.987Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43106] closed

2021-10-17T03:18:58.987Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43064] ERR: source of path 'e04f434a5122_live' has timed out

2021-10-17T03:18:58.987Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43064] closed

2021-10-17T03:18:58.988Z ring-rtsp [Front Door] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)

2021-10-17T03:18:59.003Z ring-rtsp I [-21/0] [RTSP] [session 448512404] closed

2021-10-17T03:18:59.003Z ring-mqtt [Front Door] Received set live stream state OFF

2021-10-17T03:18:59.004Z ring-mqtt [Front Door] Live video stream ended

2021-10-17T03:18:59.007Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state OFF

2021-10-17T03:18:59.007Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"inactive"}

2021-10-17T03:18:59.062Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/snapshot/image <binary_image_data>

2021-10-17T03:18:59.063Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/snapshot/attributes {"timestamp":1634440739}

2021-10-17T03:19:08.985Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43122] opened

2021-10-17T03:19:08.985Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command started

2021-10-17T03:19:09.008Z ring-rtsp [Front Door] Activating live stream via topic ring/r65866-2vl5h-0/camera/e04f434a5122/stream/command

2021-10-17T03:19:09.021Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND

2021-10-17T03:19:09.021Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state ON

2021-10-17T03:19:09.021Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"activating"}

2021-10-17T03:19:09.021Z ring-mqtt [Front Door] Establishing connection to live stream

2021-10-17T03:19:09.070Z ring-rtsp [Front Door] Live stream is activating...

2021-10-17T03:19:09.106Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"active"}

2021-10-17T03:19:09.144Z ring-rtsp [Front Door] Live stream is active!

2021-10-17T03:19:17.640Z ring-mqtt [Front Door] Failed to retrieve motion event recording URL for event

2021-10-17T03:19:18.988Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command stopped

2021-10-17T03:19:18.988Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43122] ERR: source of path 'e04f434a5122_live' has timed out

2021-10-17T03:19:18.988Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43122] closed

2021-10-17T03:19:18.988Z ring-rtsp [Front Door] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)

2021-10-17T03:19:18.997Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43150] opened

2021-10-17T03:19:18.997Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command started

2021-10-17T03:19:19.002Z ring-mqtt [Front Door] Received set live stream state OFF

2021-10-17T03:19:19.003Z ring-mqtt [Front Door] Live video stream ended

2021-10-17T03:19:19.003Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state OFF

2021-10-17T03:19:19.003Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"inactive"}

2021-10-17T03:19:19.021Z ring-rtsp [Front Door] Activating live stream via topic ring/r65866-2vl5h-0/camera/e04f434a5122/stream/command

2021-10-17T03:19:19.053Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND

2021-10-17T03:19:19.054Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state ON

2021-10-17T03:19:19.054Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"activating"}

2021-10-17T03:19:19.054Z ring-mqtt [Front Door] Establishing connection to live stream

2021-10-17T03:19:19.100Z ring-rtsp [Front Door] Live stream is activating...

2021-10-17T03:19:19.131Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"active"}

2021-10-17T03:19:19.172Z ring-rtsp [Front Door] Live stream is active!

2021-10-17T03:19:29.000Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command stopped

2021-10-17T03:19:29.000Z ring-rtsp [Front Door] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)

2021-10-17T03:19:29.000Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43150] ERR: source of path 'e04f434a5122_live' has timed out

2021-10-17T03:19:29.000Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43150] closed

2021-10-17T03:19:29.012Z ring-mqtt [Front Door] Received set live stream state OFF

2021-10-17T03:19:29.013Z ring-mqtt [Front Door] Live video stream ended

2021-10-17T03:19:29.013Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state OFF

2021-10-17T03:19:29.013Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"inactive"}

2021-10-17T03:19:29.015Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43180] opened

2021-10-17T03:19:29.015Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command started

2021-10-17T03:19:29.039Z ring-rtsp [Front Door] Activating live stream via topic ring/r65866-2vl5h-0/camera/e04f434a5122/stream/command

2021-10-17T03:19:29.051Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND

2021-10-17T03:19:29.051Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state ON

2021-10-17T03:19:29.052Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"activating"}

2021-10-17T03:19:29.052Z ring-mqtt [Front Door] Establishing connection to live stream

2021-10-17T03:19:29.101Z ring-rtsp [Front Door] Live stream is activating...

2021-10-17T03:19:29.140Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"active"}

2021-10-17T03:19:29.176Z ring-rtsp [Front Door] Live stream is active!

2021-10-17T03:19:29.326Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/snapshot/image <binary_image_data>

2021-10-17T03:19:29.326Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/snapshot/attributes {"timestamp":1634440769}

2021-10-17T03:19:39.020Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command stopped

2021-10-17T03:19:39.020Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43180] ERR: source of path 'e04f434a5122_live' has timed out

2021-10-17T03:19:39.020Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43180] closed

2021-10-17T03:19:39.020Z ring-rtsp [Front Door] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)

2021-10-17T03:19:39.024Z ring-rtsp I [-21/0] [RTSP] [conn 172.19.0.1:43206] opened

2021-10-17T03:19:39.032Z ring-rtsp I [-21/0] [path e04f434a5122_live] on demand command started

2021-10-17T03:19:39.037Z ring-mqtt [Front Door] Received set live stream state OFF

2021-10-17T03:19:39.037Z ring-mqtt [Front Door] Live video stream ended

2021-10-17T03:19:39.037Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state OFF

2021-10-17T03:19:39.038Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"inactive"}

2021-10-17T03:19:39.055Z ring-rtsp [Front Door] Activating live stream via topic ring/r65866-2vl5h-0/camera/e04f434a5122/stream/command

2021-10-17T03:19:39.068Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND

2021-10-17T03:19:39.068Z ring-mqtt [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/state ON

2021-10-17T03:19:39.068Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"activating"}

2021-10-17T03:19:39.069Z ring-mqtt [Front Door] Establishing connection to live stream

2021-10-17T03:19:39.117Z ring-rtsp [Front Door] Live stream is activating

    at TLSSocket.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/lib/api/sip.js:557:38)

2021-10-17T03:19:40.453Z ring-attr [Front Door] ring/r65866-2vl5h-0/camera/e04f434a5122/stream/attributes {"status":"active"}

2021-10-17T03:19:40.492Z ring-rtsp [Front Door] Live stream is active!
</pre>
</details>

**Comment by tsightler** [comment]
Doesn't Frigate still require a 24x7 stream to be very useful?  If so, integrating Ring camera with Frigate is unlikely to be successful.  This addon is not intended for 24x7 streaming as this is not really supported by Ring cameras/servers.

As far as why the stream fails to start, I'm afraid I don't know how to help with that.  In the logs I never actually see the publisher open, which normally happens within 2 seconds of the RTP stream being requested.  This is an ffmpeg process that starts up to publish the stream, but I don't directly control this, it's handled by ring-client-api.

Based on this, it looks like the SIP session itself is started fine, but the RTP packets never arrive.  The RTP packets use UDP and leverage STUN to open ports for the packets to get through any firewalls, my guess is this is not working in your case for whatever reason.  

Unfortunately, there's very little I can do to help troubleshoot such issues.  There's clearly nothing going wrong in the code, the stream just doesn't start.  Other than packet traces to determine if the stream is getting there or not, I don't know how you'd solve this.

You might try playing back an even stream (assuming you have a Ring protect plan) and see if that works.  Event streams play back a recorded stream from a HTTP file stored in the Ring cloud so only need TCP on port 443 to work, not SIP/RTP/UDP ports.  That might help narrow down that everything in the RTSP server parts are working, although it looks like it is.

**Comment by sebasptsch** [comment]
Thanks. I'll do some more troubleshooting and reopen if I can't figure it out.
