### ISSUE TITLE
Add support for Ring Outdoor Smart Plug

### ISSUE THREAD

**Issue by tsightler** [tsightler/ring-mqtt#310]
### Discussed in https://github.com/tsightler/ring-mqtt/discussions/304

<div type='discussions-op-text'>

<sup>Originally posted by **mopwr** January 19, 2022</sup>
Is there any chance this device could be added? 
Ring Outdoor Smart Plug - https://www.amazon.com/gp/product/B08KSJ56WR

Do you need something specific from the logs? This is the main thing I see:

2022-01-19T23:19:58.105Z ring-mqtt Unsupported device: device.beams
2022-01-19T23:19:58.105Z ring-mqtt Unsupported device: switch.beams
2022-01-19T23:19:58.105Z ring-mqtt Unsupported device: switch.beams</div>

**Comment by tsightler** [comment]
I've performed an initial push to the dev branch that includes an attempt to support these devices.  As I don't have any smart lighting, if someone that owns an Outdoor Smart Plug could give it a test and report it would be appreciated.

**Comment by mopwr** [comment]
Is it possible to test in the homeassistant addon or does it need to be a separate install?

current config is
branch: addon
debug: ring-*

**Comment by tsightler** [comment]
Just change branch config option from "addon" to "dev" and restart the addon.  To revert just change it back.

**Comment by mopwr** [comment]
2022-01-28T03:11:13.535Z ring-mqtt               switch.multilevel.beams
2022-01-28T03:11:13.537Z ring-mqtt WARNING - Unhandled Promise Rejection
ReferenceError: BeamSmartOutlet is not defined
    at getDevice (/app/ring-mqtt-dev/ring-mqtt.js:134:13)
    at updateRingData (/app/ring-mqtt-dev/ring-mqtt.js:238:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processLocations (/app/ring-mqtt-dev/ring-mqtt.js:304:5)

**Comment by tsightler** [comment]
Crap, missed that change when I decided to use a different device name.  Pushed a fix for that.

**Comment by mopwr** [comment]
Looks different now

2022-01-28T03:27:13.077Z ring-mqtt               switch.multilevel.beams
2022-01-28T03:27:13.080Z ring-mqtt WARNING - Unhandled Promise Rejection
TypeError: childDevices.find is not a function
    at new BeamOutdoorPlug (/app/ring-mqtt-dev/devices/beam-outdoor-plug.js:8:37)
    at getDevice (/app/ring-mqtt-dev/ring-mqtt.js:134:20)
    at updateRingData (/app/ring-mqtt-dev/ring-mqtt.js:238:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processLocations (/app/ring-mqtt-dev/ring-mqtt.js:304:5)

**Comment by tsightler** [comment]
Man, these are silly errors, I'm quite embarrassed not to make it past that.  I've pushed a change I hope will fix that.

**Comment by mopwr** [comment]
I think that means it is time for some sleep :) I am amazed you could make head or tails of that json device dump.

Here is the latest 

2022-01-28T03:44:36.560Z ring-mqtt               switch.multilevel.beams
2022-01-28T03:44:36.563Z ring-mqtt WARNING - Unhandled Promise Rejection
TypeError: Cannot read properties of undefined (reading 'data')
    at new BeamOutdoorPlug (/app/ring-mqtt-dev/devices/beam-outdoor-plug.js:12:38)
    at getDevice (/app/ring-mqtt-dev/ring-mqtt.js:134:20)
    at updateRingData (/app/ring-mqtt-dev/ring-mqtt.js:238:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processLocations (/app/ring-mqtt-dev/ring-mqtt.js:304:5)

**Comment by tsightler** [comment]
I pushed another change to log some extra debug info as I'm not sure why that problem is occurring so this will hopefully help me track it down.  It looks like, for some reason, the child devices are not coming through from the parent device but I've checked that code mulitple times and don't see what I'm doing wrong as it's modeled after the thermostat code which is also a multi-component device.

**Comment by mopwr** [comment]
2022-01-28T17:58:19.033Z ring-mqtt               switch.multilevel.beams
2022-01-28T17:58:19.037Z ring-mqtt WARNING - Unhandled Promise Rejection
TypeError: Cannot read properties of undefined (reading 'data')
    at new BeamOutdoorPlug (/app/ring-mqtt-dev/devices/beam-outdoor-plug.js:13:38)
    at getDevice (/app/ring-mqtt-dev/ring-mqtt.js:134:20)
    at updateRingData (/app/ring-mqtt-dev/ring-mqtt.js:238:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processLocations (/app/ring-mqtt-dev/ring-mqtt.js:304:5)

**Comment by tsightler** [comment]
Thanks @mopwr, I've pushed an update with the only thing I can thing of that might fix that error.

**Comment by mopwr** [comment]
I am going to owe you some beer after all this (or a free useless outdoor plug :) )

2022-01-28T19:34:39.560Z ring-mqtt               switch.multilevel.beams
2022-01-28T19:34:39.563Z ring-mqtt WARNING - Unhandled Promise Rejection
ReferenceError: outlet1 is not defined
    at new BeamOutdoorPlug (/app/ring-mqtt-dev/devices/beam-outdoor-plug.js:17:25)
    at getDevice (/app/ring-mqtt-dev/ring-mqtt.js:134:20)
    at updateRingData (/app/ring-mqtt-dev/ring-mqtt.js:238:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processLocations (/app/ring-mqtt-dev/ring-mqtt.js:304:5)

**Comment by tsightler** [comment]
I think I'm going to owe you since I'm wasting your time with all of my silly errors.  As you can tell, I'm not a developer!  I've fixed the above error which was yet another silly mistake on my part.  At least we are making it further, this time it almost made it through init and then there's only state and command processing, which are pretty standardized so hopefully I didn't mess those up.

**Comment by mopwr** [comment]
I hear you. I have a computer science degree but that was 16 years ago and C++ is so much different than JavaScript/JSON. I have always been more into sysadmin/network stuff.

Check out this sweetness, I can now start kicking the tires.

![Success](https://user-images.githubusercontent.com/10406031/151638633-f6ae5f84-ba73-4115-adc7-88089af0ad1f.png)

**Comment by tsightler** [comment]
Yeah, I mean, I work with developers and I can read code in most languages pretty well, but I had never written a line in Javascript until I started this project and it was with the primary goal to learn enough Javascript to feel competent, but I still make lots of silly mistakes when coding from scratch.

At least we finally have progress beyond crashing.  I'm not sure if control/status is going to be correct, I basically just implemented it the same as the smart lights since that's how it's registered, but it might not behave exactly the same way.

**Comment by mopwr** [comment]
It works to turn the outlets on and off but the state gets out of sync. Still trying to figure out what triggers it. At some point it stops updating until restarted. Sending on/off continues to work when the state doesn't.

**Comment by tsightler** [comment]
I think I know why this would happen.  From a Ring API perspective the plug is represented as three separate devices, one that represents the plug as a whole, and then two that represent the individual outlets.  While there are some other devices that are similar (fire/smoke detector for example is also two devices, although the smoke-co listener is one device with two sensors, and the thermostat is actually three devices with operation-state and temperature) with those devices the parent device is always updated whenever the child device is changed.  **UPDATE -- I was wrong, I had to address this same issue in thermostat support since, for example, temperature state might change without updating parent thermostat device**

However, with the smart plug I'm guessing that state updates for the child devices might not also update the parent device.  In the current code updates are only triggered when the parent device received an update so if child devices have updates without the parent device I could see how updates might not work.

It has to be something like this because otherwise the state code is identical to all other devices and it's literally only three lines.  I'll need to think about how to fix this.  The proper fix would be to implement proper device hierarchy support, but I don't have time for that right now so I'm thinking I can do a hackish fix by modifying data update function to look for the parent device when the child gets an update and call the parent level update function.

**Comment by tsightler** [comment]
OK, it turns out I did have to address this with the thermostat device as well, I just didn't remember doing it, so I just implemented the same "fix" that I used there in the outdoor plug device.  You can restart and pull the newest dev code and I think, if I didn't break it in some way, that it will fix this issue.  It's a pretty straightforward fix so hopefully I didn't break anything.

**Comment by mopwr** [comment]
That seems to have fixed it, Updates are almost instant now when switched in HA or Ring app.

**Comment by tsightler** [comment]
Thanks a lot for the testing, I'll queue up this change for the 4.9.1 release which is soon.

**Comment by mopwr** [comment]
Thanks for your work and patience on this. It is much appreciated.

**Comment by tsightler** [comment]
Version 4.9.1 has been pushed and includes support for the Outdoor Smart Plug. Thanks for the testing!

**Comment by mopwr** [comment]
Looks like it may still have the extra debug logging code turned on in case you don't want that.

![image](https://user-images.githubusercontent.com/10406031/152070287-5d6f48fa-5306-4d9f-bebc-9f6e5c5b1903.png)

**Comment by tsightler** [comment]
That's just standard discovery data logging, that's been part of the debug log output for a long time.
