### ISSUE TITLE
Camera Snapshot Image corrupted 

### ISSUE THREAD

**Issue by junalmeida** [tsightler/ring-mqtt#341]
### Describe the bug
Apparently random, some of the still images show corrupted. It seems totally random, although it happens very often, some works with no problem. Below an example:

![image](https://user-images.githubusercontent.com/991675/160130871-bfd83d69-9b5e-4ed6-a578-bf6dc74b35e0.png)

### Describe your environment
Home assistant OS on a Raspberry Pi 4. Plenty of RAM available. Up-to date HA. Ring-mqtt runs as home assistant add-on, so does the  Mosquitto itself. The Raspberry machine is hooked to an ethernet cable, not wifi.

### Describe your settings and what you've tried

```
enable_cameras: true
snapshot_mode: motion
livestream_user: ''
livestream_pass: ''
enable_modes: false
enable_panic: false
beam_duration: 0
disarm_code: 'REDACTED'
mqtt_host: <auto_detect>
mqtt_port: <auto_detect>
mqtt_user: <auto_detect>
mqtt_password: <auto_detect>
branch: addon
debug: ring-*
ring_token: ''
location_ids:
  - ''

```

### Debug Logs
```
2022-03-25T13:32:49.216Z ring-mqtt [Front Door] Failed to retrieve motion event recording URL for event
2022-03-25T13:32:50.572Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/attributes {"lastMotion":1648214612,"lastMotionTime":"2022-03-25T13:23:32Z","personDetected":false,"motionDetectionEnabled":true}
2022-03-25T13:32:50.573Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/state ON
2022-03-25T13:32:50.573Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/attributes {"status":"active"}
2022-03-25T13:32:50.574Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/event_stream/state OFF
2022-03-25T13:32:50.575Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/event_stream/attributes {"status":"inactive"}
2022-03-25T13:32:50.575Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/event_select/state Motion 1
2022-03-25T13:32:50.576Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/event_select/attributes {"recordingUrl":null,"eventId":null}
2022-03-25T13:32:50.577Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/state OFF
2022-03-25T13:32:50.578Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/attributes {"lastMotion":1648214612,"lastMotionTime":"2022-03-25T13:23:32Z","personDetected":false,"motionDetectionEnabled":true}
2022-03-25T13:32:50.578Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/ding/state OFF
2022-03-25T13:32:50.579Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/ding/attributes {"lastDing":1648169194,"lastDingTime":"2022-03-25T00:46:34Z"}
2022-03-25T13:32:50.580Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/snapshot/image <binary_image_data>
2022-03-25T13:32:50.581Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/snapshot/attributes {"timestamp":1648214625}
2022-03-25T13:32:50.856Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/info/state {"batteryLevel":null,"firmwareStatus":"Up to Date","lastUpdate":"2022-03-25T13:32:32Z","wirelessNetwork":"Binarius","wirelessSignal":-83,"stream_Source":"rtsp://03cabcc9-ring-mqtt:8554/54e019c6883c_live","still_Image_URL":"https://homeassistant:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}"}
2022-03-25T13:32:50.857Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/wireless/attributes {"wirelessNetwork":"Binarius","wirelessSignal":-83}
2022-03-25T13:32:50.858Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/battery/attributes {"batteryLevel":null}
2022-03-25T13:33:29.766Z ring-mqtt [Front Door] Failed to retrieve motion event recording URL for event
2022-03-25T13:34:30.599Z ring-mqtt [Front Door] Failed to retrieve motion event recording URL for event
2022-03-25T13:35:31.619Z ring-mqtt [Front Door] Failed to retrieve motion event recording URL for event
2022-03-25T13:35:38.913Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/info/state {"batteryLevel":null,"firmwareStatus":"Up to Date","lastUpdate":"2022-03-25T13:35:16Z","wirelessNetwork":"Binarius","wirelessSignal":-83,"stream_Source":"rtsp://03cabcc9-ring-mqtt:8554/54e019c6883c_live","still_Image_URL":"https://homeassistant:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}"}
2022-03-25T13:35:38.922Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/wireless/attributes {"wirelessNetwork":"Binarius","wirelessSignal":-83}
2022-03-25T13:35:38.923Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/battery/attributes {"batteryLevel":null}
2022-03-25T13:36:32.394Z ring-mqtt [Front Door] Failed to retrieve motion event recording URL for event
2022-03-25T13:36:42.700Z ring-rtsp INF [RTSP] [conn 172.30.32.1:41544] closed (terminated)
2022-03-25T13:36:42.703Z ring-rtsp INF [RTSP] [session 931285196] closed (teared down by 172.30.32.1:41544)
2022-03-25T13:36:47.700Z ring-rtsp INF [path 54e019c6883c_live] runOnDemand command stopped
2022-03-25T13:36:47.701Z ring-rtsp INF [RTSP] [conn 127.0.0.1:39320] closed (terminated)
2022-03-25T13:36:47.701Z ring-rtsp INF [RTSP] [session 242602280] closed (terminated)
2022-03-25T13:36:47.702Z ring-rtsp [Front Door] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-03-25T13:36:47.716Z ring-mqtt [Front Door] Received set live stream state OFF
2022-03-25T13:36:47.722Z ring-mqtt [Front Door] Live video stream ended
2022-03-25T13:36:47.723Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/state OFF
2022-03-25T13:36:47.723Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/attributes {"status":"inactive"}
2022-03-25T13:36:47.731Z ring-rtsp ./scripts/start-stream.sh: line 34: [: 1726: binary operator expected
```

Please let me know if I can change any setting to provide a better log.

**Comment by tsightler** [comment]
Unfortunately, this might not be quite enough logs as it's missing the actual motion event and messages that would tell me how the snapshot was retrieved, but I'll try to make some assumptions

This looks like a battery powered camera, but I'm a little confused because the battery level says null.  Battery powered cameras can't take snapshots while recording, and, since motion events start recordings, the only option is to start a local stream and attempt to grab a still frame from it.  It currently tries to grab the first full keyframe in the stream, but, in some cases, Ring cameras have a lot of errors in the early part of the stream.  This is generally far worse for cameras with poor connections, and you have one of the weakest signals I've ever seen from a camera that otherwise works ("wirelessSignal":-83).  To give an example, I have a few floodlights at the corner edges of my home that I consider to have borderline signal, and those are in the -65 to -70 range, your -83 is barely above the noise floor of a wireless signal which is generally around -90dBm.  I'm not saying a better signal would absolutely eliminate this issue, but it could be a contributing factor as to why you see it so regularly.

Unfortunately, I don't have any way to detect when this is happening because the capture just relies on FFmpeg parsing out the image from the stream and it will still spit out an image even if there's corrupt/missing inbound packets.  Maybe there's some way to get FFmpeg to not do that, but I haven't found it and, honestly, I'm leaning toward removing support for motion snapshots for battery cameras completely (and maybe removing all video support for battery cameras).  Perhaps one day Ring will give 3rd parties access to the push snapshots, but so far I don't think it's happened.

**Comment by junalmeida** [comment]
It is a wired doorbell, no battery. 

I will try to improve the wifi signal and I will get back to you if problem persists, but I must add that even with this poor signal, still image shows correct on Ring app. I don't know if you pull the image directly from the device or the Ring servers, which would make a different on that case.

**Comment by tsightler** [comment]
What model camera is it?  Without full logs I can't see what specific model. You say it's wired, but is it a battery capable camera that is simply wired to power?  If so, in the Ring ecosystem, that still counts as a battery powered camera from a functionality perspective.  The code appears to be detecting it as a battery capable camera without a battery, which is why battery status is shown as "unknown".  If you truly have a wired power only camera (like the Doorbell Pro), then it would be worth investigating via full logs.

All data is pulled from Ring servers, however, the image you see in the Ring app is from a push API and my understanding is that Ring limits this API access to its own apps, at least, it's not available to me via the ring-client-api library that this project uses for access to Ring API servers.  You can read about the snapshot limitations of that API here:  https://github.com/dgreif/ring/wiki/Snapshot-Limitations

Because I can't access this image, the only options left are to either wait for the recording to be done and then send a stale image (as ring-homebridge does), or start a live stream and try to grab a still image from the stream.  The current code attempts the latter approach, but it's of course more error prone as it relies on the 100% of RTP packets for the requested keyframe arriving and being processed in a timely manner.  Note that this might not even be noticeable when watching the video stream since additional corrective packets may come in almost immediately, so it might just be a glitch of a few milliseconds, but, because an image grab is an instantaneous view of that stream, it still shows up there.

I've tested this code extensively across the 7 cameras I own, although none of them are battery cameras so they don't have snapshot limitations, but I force the code to use the battery camera logic even for my wired cameras.  Of those 7 cameras, 2 are wired ethernet, the remaining 5 are wireless.  If I walk around my home to trigger the cameras I will get about 1 corrupted image per 15 snapshot images, but almost all will come from the wireless cameras with the weakest signal, and nearly none from the wired cameras.

Unfortunately, there's just not much I can do about it.  I knew from the start that this method would not be 100% reliable, and would be worse for people with weaker Wifi or poor upstream bandwidth, but again, the only other available option is no snapshot at all and it seemed reliable enough for me and the other testers to be usable, so I released it as is and it's been in the code this way for nearly a year and you're the first person to ever open an issue on it so I'm thinking that it must work good enough for most people.  Perhaps one day we will get access to the snapshot push API and this problem will go away completely, there is some work ongoing for a new snapshot API for v10 of ring-client-api.

One thing that would be interesting, if you login to both the Ring app on your phone/tablet as well as the Ring web app (or perhaps just on another phone), and you start a live stream to that camera, does the snapshot in the app continue to refresh on the other device while the live stream to that camera is active?  If so, it might mean that the new snapshot API is not as limited in this regard, but, as I have no battery cameras, I have no way to test it.

**Comment by tsightler** [comment]
BTW, one common cause of this issue is the lack of UDP buffer allocation in the default Linux setup which is a paltry 200K.  When a stream is first started the RTP packets come flying in faster than Node can get the pipeline started and fully processing, especially on low-power systems like RPi with their overall slow ARM processors (it runs NodeJS about 4x slower than an equivalent Intel CPU of similar clock speed).  Overall, there's still enough CPU to handle it, but, as NodeJS is single threaded it spends a few hundred milliseconds of CPU time getting the pipeline setup but that causes the early parts of the stream to lose a lot of packets because UDP has no flow control, so anything that makes it to the system after the 200K buffer is full is just lost forever.  It causes exactly the behavior you show in the image.

You can dramatically improve this behavior by increasing the default net.core.rmem_max/rmem_default values.  Even just going to something like 1MB make a huge difference in reliability in the early parts of the stream.  Unfortunately, these values can't be changed from within the container in which the addons run, and so the only way to make the change is to get developer access to the actual host OS console over SSH via port 22222.  This requires creating an authorized_keys file with an SSH public key, copying it to a specially labeled USB drive, and then importing it via the UI (or reboot).  Even then, Home Assistant OS is so locked down that there are very few ways to make and type of change persistent, but I've created a small udev rule file that can be dropped into the /etc/udev/rules.d which is one of the few places that seems to support persistent files.  I still haven't tested this after an OS upgrade, but it at least survives a reboot.

This is a pain, and it somewhat makes me regret ever agreeing (begrudgingly) to support this project as an HA addon, but I don't really know how else to address this.  These great systems that are designed to be "easy" make tweaking for specific use cases far more difficult.  However, if you are interested in applying this file to test, let me know, I'll be happy to share it.

**Comment by junalmeida** [comment]
https://ring.com/products/video-doorbell-wired

This is the doorbell I own. It does not have a battery.

**Comment by junalmeida** [comment]
I just made the test you asked, I log in on both mobile app and web app on computer and I can see snapshots updated after I started the live stream. 

I can try your suggestion about changing UDP buffer.

**Comment by tsightler** [comment]
No need to change the UDP buffer as it looks like your camera should be identified as line powered camera, which would not have the issues I describe above.  If you are willing to send full logs to my email address I'll reopen this issue and we can investigate.  My guess is that ring-client-api is not identifying the model correctly.

Can you try the dev branch?  It uses a much newer API which has added some code for properly identifying more recent camera variants.  That API version is still in beta, but I think the author will release the final version soon-ish.  If it works, then we'll know that's the reason it's being identified incorrectly, although I could maybe work around it in other ways.

**Comment by junalmeida** [comment]
Yep I will look on how to switch to the dev branch of your addon! And I'm not sur on how to record the full log of the add-on as the UI only show a tail. Btw the log setting of your add-on is `debug: ring-*`

**Comment by tsightler** [comment]
Just change "branch: addon" in the config to "branch: dev" and restart to test the development branch.

You'll need to use docker tools or something similar to get full logs.  Maybe you can just catch it at the right time, but, unfortunately, HA UI provides too few logs in most cases.

https://github.com/tsightler/ring-mqtt-ha-addon/blob/master/GET-LOGS.md

**Comment by junalmeida** [comment]
Ok I now have a complete log. Could you share your email address?

**Comment by tsightler** [comment]
It's the same as my Github username at gmail.  Thanks!

**Comment by junalmeida** [comment]
logs sent.

**Comment by tsightler** [comment]
I don't see any motion events in the logs you sent.  Those logs are from the development version and it appears to be correctly identifying the cameras as a wired camera as there is no battery information in those logs (unlike the log snipped you posted originally).  Have you verified if the problem still occurs with the development version?  I would expect not but, if so, I need logs that include the motion event and snapshot capture.

Also, there are lots of failures about recording URL.  These are non-critical but it's more for my education, do you have a Ring protect plan that allows recordings to be stored by Ring?  I'm thinking that you don't and I need to detect that situation to stop the errors.

**Comment by junalmeida** [comment]
I will probably need some time to be sure, as this occurs randomly. I will also pass in front of it because this street is very quiet lol 

I do not have a protection plan.

**Comment by tsightler** [comment]
OK, well, even logs from a single motion event would tell a lot as it will let me know for sure that the camera is being properly detected as a wired camera and using the fast/reliable getSnapshot method vs the slower and less reliable capture frame from stream method that it appears was used in the screenshot and original post.  Just let me know.

**Comment by junalmeida** [comment]
Just sent you another log that should have 1 motion event.

**Comment by tsightler** [comment]
So it's interesting, the code used the fast/reliable getSnapshot method as it would with a wired camera, however, the camera itself behaved like a battery camera:

```
2022-04-01T16:12:50.635Z ring-mqtt [Front Door] Camera received motion ding at 1648829570, expires in 179 seconds
2022-04-01T16:12:50.637Z ring-mqtt [Front Door] Requesting an updated motion snapshot
2022-04-01T16:12:50.638Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/state ON
2022-04-01T16:12:50.640Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/attributes {"lastMotion":164882
9570,"lastMotionTime":"2022-04-01T16:12:50Z","personDetected":false,"motionDetectionEnabled":true}
2022-04-01T16:13:25.698Z ring-mqtt [Front Door] Successfully retrieved updated snapshot
```

You can see here that ring-mqtt detected a motion event and immediately, .002 seconds later, requested an updated snapshot via the API.  However, the snapshot didn't update until 35 seconds later, which is pretty much exactly the record time.  This means that even though this is a line-powered camera, it has the limitations of a battery camera, i.e. it is unable to take a snapshot while recording.

To give you an example of how true line-powered camera should behave, here's a similar snippet from my own Doorbell Pro camera:

```
2022-04-01T16:32:33.403Z ring-mqtt [Front Doorbell] Camera received motion ding at 1648830753, expires in 176 seconds
2022-04-01T16:32:33.404Z ring-mqtt [Front Doorbell] Requesting an updated motion snapshot
2022-04-01T16:32:33.404Z ring-mqtt [Front Doorbell] ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a11f710d/motion/state ON
2022-04-01T16:32:33.405Z ring-attr [Front Doorbell] ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a11f710d/motion/attributes {"lastMotion":1648830753,"lastMotionTime":"2022-04-01T16:32:33Z","personDetected":true,"motionDetectionEnabled":true}
2022-04-01T16:32:33.536Z ring-mqtt [Front Doorbell] Successfully retrieved updated snapshot
2022-04-01T16:32:33.536Z ring-mqtt [Front Doorbell] ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a11f710d/snapshot/image <binary_image_data>
```
Notice in this case it is the same, an almost immediate request for a snapshot update, but instead of taking 35 seconds, the new snapshot was received only 132ms later and immediate published via MQTT.  This is still good information, because it means I need to modify the code to detect these cameras and behave as battery cameras when attempting to grab a snapshot.

However, that just means you are still stuck with the potential to get corrupt images sometimes.  Later tonight I'll type up the instructions on how to increase the UDP buffer size on Home Assistant OS and you can try that if you want to.  I'm not sure what else I'd be able to do, maybe I can figure out some magic with ffmpeg to throw away the incomplete frames, but I'm not sure.

**Comment by junalmeida** [comment]
![2022-04-02_14-46-51](https://user-images.githubusercontent.com/991675/161398999-7d3db903-1909-4fb0-b19c-1c8a52ab7212.jpg)

Just to let you know using dev branch didn't work.

**Comment by tsightler** [comment]
Can you pleaee provide logs from that event?

**Comment by tsightler** [comment]
Please try the latest dev branch released tonight (just restart the addon to pull the latest changes).  The maintainer of ring-client-api was able to get push notification working in his latest beta release and I've modified ring-mqtt to use this new method for retrieving snapshots for motion events, that should let Home Assistant get the same image as the one in the Ring apps which is a major step forward.

If you still have any issue please provide a log that includes the event where the corrupted image occurred.

**Comment by junalmeida** [comment]
Oh that is good news then, I will try it right now and let you know as soon as possible.

**Comment by jeffgraham-hub** [comment]
Just as an FYI...
 Even though I have no known issues with the current version I was going to try the dev branch to test the new method for snapshots. However, I am getting the below error on start up. I am no developer but is "const utils = require( '../lib/utils' )" missing from beam.js? Let me know if you need more info.

2022-04-05T15:59:25.307Z ring-mqtt New location: Home (xxxxxxx)
2022-04-05T15:59:27.358Z ring-mqtt   New device: Home Bridge (xxxxxxx)
2022-04-05T15:59:27.358Z ring-mqtt               adapter.ringnet
2022-04-05T15:59:27.364Z ring-mqtt WARNING - Unhandled Promise Rejection
ReferenceError: utils is not defined
    at Beam.initLightEntity (/app/ring-mqtt-dev/devices/beam.js:56:9)
    at Beam.init (/app/ring-mqtt-dev/devices/beam.js:25:22)
    at EventEmitter.<anonymous> (/app/ring-mqtt-dev/devices/base-ring-device.js:33:18)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.<anonymous> (/app/ring-mqtt-dev/lib/state.js:35:29)
    at EventEmitter.emit (node:events:390:28)
    at new RingSocketDevice (/app/ring-mqtt-dev/devices/base-socket-device.js:22:21)
    at new Beam (/app/ring-mqtt-dev/devices/beam.js:5:9)
    at RingMqtt.getDevice (/app/ring-mqtt-dev/lib/ring.js:292:24)
    at RingMqtt.updateRingData (/app/ring-mqtt-dev/lib/ring.js:206:45)

**Comment by tsightler** [comment]
Well, it's dev, so it can be broken at any time.  It's had like 50 commits in just the last few days because v5 is a major refactor.  I try to keep it mostly working for the stuff that I have in my environment because I run the dev branch on my dev instance, but I don't have smart lighting, so sometimes the stuff I don't personally have in the environment stays broken longer.

The actual issue is that I'm in the process of removing beam_duration as, in v5, it will no longer be a global config option, but I didn't get it done this weekend so it's in a half-done state.  Adding utils back probably would fix it for now.

**Comment by jeffgraham-hub** [comment]
I understand that it is dev and I can certainly wait. I was just going to give it a test. Thank you for the feedback.

**Comment by tsightler** [comment]
I put the require back for now since I won't have time to mess with this code over the coming few days, hopefully that will fix it.

Some important notes about current dev branch, v5 is a pretty significant refactor and, while it should still be possible to go back with the existing config, this is untested, so be aware that there's at least a chance you may have to reinstall if things go really awry.  I don't expect this as I'm running the dev branch on both of my instances, but just something to be aware of.

There are major changes in v5:

1) Cameras use WebRTC instead of SIP for streaming.  This has the advantage that the RTP stream from Ring is now fully encrypted using standard DTLS/SRTP encryption algorithm, and also it can support cameras configured to use Ring Edge, however, it also comes with some disadvantages in that, because NodeJS has no native WebRTC implementation, the code uses a werift, which is a typescript/javascript native solution that, while very powerful and reliable, requires quite a bit more memory and, more importantly, CPU (mainly due to the overhead of encryption), which is especially noticeable on lower end hardware.  It should still work OK (I use it on an RPi4 myself), but just something to be aware of.

2) Snapshot settings are no longer global and the settings in the config file for this are ignored.  Instead, there is now a config  options for each camera and the mode can be set dynamically and will be remembered, including the interval.  The default behavior is "auto", which is motion snapshots for all cameras and interval snapshots only for battery cameras.

3) For addons, it should be painless(hopefully), for Docker installs, persistent mount is now required (it was already highly recommended), for standard installs, ring-state.json file is now required so ability to write to directory is required.

Good luck!

**Comment by tsightler** [comment]
Also, another important note, while the push notifications are really nice, they are, in some ways, slightly less functional than the prior "poll for ding" method in that they rely 100% on notifications being enabled.  So, for example, if you use the smart notifications feature in the Ring app to disable notifications except when a person is detected, that's also the only notifications that will come to the addon, while, previously, the addon would still see all motion events.  It's an important change in behavior, and one I'm not sure I'm completely happy with as I make significant use of smart notifications.   I think can work around it by using a different login for my phone vs the addon since I believe notifications are set per-user, but I haven't tested this yet and it's still less than ideal, IMO.

**Comment by junalmeida** [comment]
FYI getting a lot of 
```
2022-04-07T22:29:43.992Z ring-mqtt [Front Door] Error: Snapshot for Front Door (doorbell_graham_cracker - Doorbell Wired) failed to refresh after 15 seconds
2022-04-07T22:29:43.992Z ring-mqtt [Front Door] Failed to retrieve updated snapshot
```

After a restart. I will try restart again to check the version.

**Comment by junalmeida** [comment]
Now current version is; 
``` 
ring-mqtt.js version: 5.0.0-beta3
Node version v16.14.0
NPM version 8.3.1
git version 2.20.1
``` 

``` 
states.camera.front_door_snapshot.attributes.entity_picture }}"}
2022-04-07T23:42:03.009Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/wireless/attributes {"wirelessNetwork":"Binarius","wirelessSignal":-51}
2022-04-07T23:43:43.953Z ring-mqtt [Front Door] Received motion push notification, expires in 180 seconds
2022-04-07T23:43:43.954Z ring-mqtt [Front Door] Requesting an updated motion snapshot
2022-04-07T23:43:43.955Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/state ON
2022-04-07T23:43:43.957Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/motion/attributes {"lastMotion":1649375023,"lastMotionTime":"1970-01-20T02:09:35Z","personDetected":false,"motionDetectionEnabled":true}
2022-04-07T23:43:46.995Z ring-rtsp INF [RTSP] [conn 172.30.32.1:55106] opened
2022-04-07T23:43:47.021Z ring-rtsp INF [path 54e019c6883c_live] runOnDemand command started
2022-04-07T23:43:47.058Z ring-rtsp [Front Door] Requesting activation of live stream via MQTT
2022-04-07T23:43:47.082Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND
2022-04-07T23:43:47.082Z ring-mqtt [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/state ON
2022-04-07T23:43:47.084Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/attributes {"status":"activating"}
2022-04-07T23:43:47.085Z ring-mqtt [Front Door] Requesting a live stream session via Ring API
2022-04-07T23:43:47.111Z ring-rtsp [Front Door] MQTT message indicates that live stream is activating
2022-04-07T23:43:47.399Z ring-mqtt [Front Door] Live stream assigned to worker 1 with 0 current active sessions
2022-04-07T23:43:48.548Z ring-mqtt [Front Door] Live stream has been successfully activated
2022-04-07T23:43:48.549Z ring-attr [Front Door] ring/c822d046-e2a3-4946-a364-e682805d2625/camera/54e019c6883c/stream/attributes {"status":"active"}
2022-04-07T23:43:48.568Z ring-rtsp [Front Door] MQTT message indicates that live stream is active
2022-04-07T23:43:51.361Z ring-rtsp INF [RTSP] [conn 127.0.0.1:50626] opened
2022-04-07T23:43:51.364Z ring-rtsp INF [RTSP] [session 820957970] opened by 127.0.0.1:50626
2022-04-07T23:43:51.373Z ring-rtsp INF [RTSP] [session 820957970] is publishing to path '54e019c6883c_live', 3 tracks with TCP
2022-04-07T23:43:51.377Z ring-rtsp INF [RTSP] [session 499030449] opened by 172.30.32.1:55106
2022-04-07T23:43:51.385Z ring-rtsp INF [RTSP] [session 499030449] is reading from path '54e019c6883c_live', 3 tracks with TCP
2022-04-07T23:43:58.963Z ring-mqtt [Front Door] Error: Snapshot for Front Door (doorbell_graham_cracker - Doorbell Wired) failed to refresh after 15 seconds
2022-04-07T23:43:58.963Z ring-mqtt [Front Door] Failed to retrieve updated snapshot
```
It's been a while since I don't see an updated snapshot, not sure when exactly this stopped working with the dev branch.

**Comment by tsightler** [comment]
Based on this log, the push notification being received by ring-mqtt does not include the image_uuid property so it is just requesting a normal snapshot which your camera cannot provide since it can't take a snapshot while recording.  Do you have the Rich Notifications feature enabled on this camera (select the camera/doorbell then Device Settings...Notification Settings...Rich Notifications and verify it is enabled).  I'm wondering if this requires a Ring subscription which you said you do not have.

Also, your log appears to show a near immediate connection to the livestream after the motion event.  Did you trigger this yourself or do you have some automation doing this?  Just curious.

**Comment by tsightler** [comment]
After some additional research it seems that the rich notification feature requires a Ring Protect subscription, so that means you will not be able to get a motion snapshot at all with v5 of ring-mqtt since you indicated above that you do not have a Ring Protect subscription.  I will attempt to modify the code to detect this somehow and at least log the reason why an image isn't available, but I think we're at an impasse since I'm removing the old method of grabbing from the stream in v5.

Due to this, I will likely close this issue unless you have some additional information.

**Comment by junalmeida** [comment]
Rich notifications indeed require a subscription (what doesn't require right!?), which I don't have.
And yes I do have an automation to record for a minute after a motion event. I am now taking a snapshot out of the recording itself because the native snapshot entity can't be updated, and the recording starts before the snapshot arrives.

Feel free to close the issue. My suggestion here is to make it clear on the logs when and why it fails to update a snapshot. I believe, once you may have ways to check if the video stream is active, you could grab the snapshot out of the stream?

**Comment by tsightler** [comment]
The biggest issue is that it's very difficult to know if it's possible to take a snapshot or not.  In the past you could check if the camera was a battery camera, but as we've now seen, your camera is technically not a battery camera, but still behaves like a battery camera.  I have all wired cameras only and they all take a snapshot on motion in any case.

Because of this, it's very difficult to know for sure why a camera failed the snapshot request and thus difficult to log any accurate and useful message other than the fact that it failed.  The only way to know for sure is if Ring actually documented all of these things in their specs, or if I had access to every single camera model, which I most certainly do not.

I've removed the code to get snapshots from the stream and I don't plan to re-implement this, although users can of course get them from the HA camera service.  Extracting snapshots from the stream directly with ffmpeg was never super reliable (thus the reason for you opening this issue to begin with), and the vast majority of users do have at least a basic subscription, so the notification snapshots should work for them.  For users with battery cameras that don't have a subscription, they'll just have to live with the limitations of no subscription.

**Comment by tsightler** [comment]
@junalmeida Would you be willing to run [Data Discovery](https://github.com/dgreif/ring/wiki/Data-Discovery) and sharing the output.  The author of ring-client-api has some idea how to detect if a camera supports snapshots while recording other than just using the battery state.  If you could share the output from your camera that would help us verify if this method would work.

**Comment by junalmeida** [comment]
@tsightler here it goes
[ring-doorbell.json.txt](https://github.com/tsightler/ring-mqtt/files/8473579/ring-doorbell.json.txt)

**Comment by tsightler** [comment]
Thank you!
