### ISSUE TITLE
WARNING - Unhandled Promise Rejection & Uncaught Exception (Siren Volume)

### ISSUE THREAD

**Issue by roylofthouse** [tsightler/ring-mqtt#352]
### Describe the bug

Update to latest DEV branch results in WARNING - Unhandled Promise Rejection and Uncaught Exception
### Describe your environment

core-2022.4.1
supervisor-2022.03.5
Home Assistant OS 7.6

### Configuration:
enable_cameras: true
snapshot_mode: all
livestream_user: ''
livestream_pass: ''
enable_modes: false
enable_panic: false
beam_duration: 0
disarm_code: ''
mqtt_host: <auto_detect>
mqtt_port: <auto_detect>
mqtt_user: <auto_detect>
mqtt_password: <auto_detect>
branch: dev
debug: ring-*
ring_token: ''
location_ids ''

### Describe your settings and what you've tried

Following an update to 2022.4.0 & 4.1, the following errors started occurring.
I am able to return to branch: addon but lose Siren Volume control (showing NaN on slider). 

The slider still works in the dev version (and sets correctly in Ring), but any change to Ring Alarm results in Ring MQTT restarting. 

### Debug Logs
**At startup:**

WARNING - Unhandled Promise Rejection
TypeError: this.publishState is not a function
    at Siren.publish (/app/ring-mqtt-dev/devices/base-socket-device.js:32:18)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)

**Adjusting Siren Volume / Setting or Disarming the Alarm:**

ERROR - Uncaught Exception
TypeError: this.publishState is not a function
    at /app/ring-mqtt-dev/devices/base-socket-device.js:18:41
    at Object.next (/app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/Subscriber.js:161:21)
    at SafeSubscriber.Subscriber._next (/app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/Subscriber.js:101:26)
    at SafeSubscriber.Subscriber.next (/app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at /app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/Subject.js:66:34
    at Object.errorContext (/app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at BehaviorSubject.Subject.next (/app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/Subject.js:58:24)
    at BehaviorSubject.next (/app/ring-mqtt-dev/node_modules/rxjs/dist/cjs/internal/BehaviorSubject.js:48:31)
    at RingDevice.updateData (/app/ring-mqtt-dev/node_modules/ring-client-api/lib/api/ring-device.js:26:21)
    at /app/ring-mqtt-dev/node_modules/ring-client-api/lib/api/ring-device.js:23:41

**Comment by tsightler** [comment]
Hmm...somehow missed the rename on that function during the recent bulk rename operations.  Not sure how since I used global search/replace, but hopefully it should be fixed now.

**Comment by roylofthouse** [comment]
Thank you sir. All working now.  Really appreciate all your hard work.
