### ISSUE TITLE
Error after upgrading to version 5.0.4

### ISSUE THREAD

**Issue by muneeb1990** [tsightler/ring-mqtt#480]
### Describe the Bug

Seems like the add-on is stuck in a loop. It keeps getting this error and restarts the add-on, runs into this error again and so on. I haven't changed any configuration for this add-on. I'm using Ring Video Doorbell 2 with a Chime pro.  

### Steps to Reproduce

n/a

### Expected Behavior

No error

### Log Output

```shell
2022-10-13T23:40:06.387Z ring-rtsp [Front Door] Deactivating event stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-10-13T23:40:06.392Z ring-mqtt [Front Door] The recorded ding event stream has ended
2022-10-13T23:40:06.392Z ring-mqtt [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/event_stream/state OFF
2022-10-13T23:40:06.392Z ring-attr [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/event_stream/attributes {"status":"inactive"}
2022-10-13T23:40:06.399Z ring-mqtt [Front Door] Received set event stream state OFF
2022-10-13T23:40:06.400Z ring-mqtt ERROR - Uncaught Exception
TypeError: Cannot set properties of undefined (setting 'status')
    at Camera.setEventStreamState (/app/ring-mqtt/devices/camera.js:977:51)
    at Camera.processCommand (/app/ring-mqtt/devices/camera.js:824:22)
    at EventEmitter.<anonymous> (/app/ring-mqtt/devices/base-ring-device.js:166:34)
    at EventEmitter.emit (node:events:513:28)
    at MqttClient.<anonymous> (/app/ring-mqtt/lib/mqtt.js:139:25)
    at MqttClient.emit (node:events:513:28)
    at MqttClient._handlePublish (/app/ring-mqtt/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/ring-mqtt/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/ring-mqtt/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/app/ring-mqtt/node_modules/mqtt/lib/client.js:452:5)
2022-10-13T23:40:07.402Z ring-mqtt The ring-mqtt process is shutting down...
2022-10-13T23:40:07.404Z ring-mqtt Setting all devices offline...
2022-10-13T23:40:08.406Z ring-mqtt [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/status offline
2022-10-13T23:40:08.407Z ring-mqtt [Lounge] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/chime/0035fff23ba5/status offline
2022-10-13T23:40:09.175Z ring-attr [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/motion/attributes {"lastMotion":0,"lastMotionTime":"","personDetected":false,"motionDetectionEnabled":false}
2022-10-13T23:40:09.176Z ring-mqtt [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/stream/state OFF
2022-10-13T23:40:09.176Z ring-attr [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/stream/attributes {"status":"inactive"}
2022-10-13T23:40:09.177Z ring-mqtt [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/event_stream/state OFF
2022-10-13T23:40:09.178Z ring-attr [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/event_stream/attributes {"status":"inactive"}
2022-10-13T23:40:09.179Z ring-mqtt [Front Door] ring/f6297b79-8b56-4fbd-86ab-8e7afdc053d1/camera/4c24988892f4/event_select/state Ding 1
```

### Config File

```shell
mqtt_url: mqtt://iamamosquito:mqttbroker@192.168.1.161
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: true
enable_panic: false
branch: addon
debug: ring-*
location_ids:
  - ""
```

### Install Type

Home Assistant Add-on

### Version

5.0.4

### Operating System

Ubuntu Server 22.04

### Architecture

x86_64

### Machine Details

HP Prodesk G600

**Comment by tsightler** [comment]
Thanks for reporting.  It's not really anything to do with 2022.10.3, rather it's a bug that somehow slipped into 5.0.4 due to a major typo!  I'm not really sure how that happened but I'll have to push out a 5.0.5 to fix it.

**Comment by muneeb1990** [comment]
Ah ok! I wasn’t sure which one as I upgraded both on the same day. Thanks for the quick response though!

**Comment by tsightler** [comment]
Version 5.0.5 has been pushed so you can upgrade and things should be fixed.

**Comment by muneeb1990** [comment]
> Version 5.0.5 has been pushed so you can upgrade and things should be fixed.

Yep, all good now. Just had to regenerate the token. Thanks again!
