### ISSUE TITLE
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input)

### ISSUE THREAD

**Issue by shimmers1** [tsightler/ring-mqtt#630]
Hello,

The ring-mqtt works perfectly as soon as I restart HA but then over time the camera just goes unavailable with the following errors from the log:

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input)

**Comment by tsightler** [comment]
Please provide full logs from restart until failure.  If you don't want to share them here you can send them to my personal mail (same username at gmail) and simply reference this case.

**Comment by tsightler** [comment]
Critical error is here:

```
2023-05-12T22:11:06.167Z ring-rtsp panic: runtime error: invalid memory address or nil pointer dereference
2023-05-12T22:11:06.168Z ring-rtsp [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7c665f]
2023-05-12T22:11:06.168Z ring-rtsp
2023-05-12T22:11:06.168Z ring-rtsp goroutine 111 [running]:
2023-05-12T22:11:06.168Z ring-rtsp github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc00015c6e0?)
2023-05-12T22:11:06.168Z ring-rtsp      github.com/AlexxIT/go2rtc/cmd/streams/producer.go:61 +0x9f
2023-05-12T22:11:06.168Z ring-rtsp github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc000144380, {0xd466f0, 0xc000222700})
2023-05-12T22:11:06.168Z ring-rtsp      github.com/AlexxIT/go2rtc/cmd/streams/stream.go:69 +0x4b4
2023-05-12T22:11:06.169Z ring-rtsp github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xb2e400?, 0xd3ff30?})
2023-05-12T22:11:06.169Z ring-rtsp      github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:181 +0x5d0
2023-05-12T22:11:06.169Z ring-rtsp github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
2023-05-12T22:11:06.169Z ring-rtsp      github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
2023-05-12T22:11:06.169Z ring-rtsp github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc000222700)
2023-05-12T22:11:06.169Z ring-rtsp      github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:92 +0xb88
2023-05-12T22:11:06.169Z ring-rtsp github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc000222700)
2023-05-12T22:11:06.169Z ring-rtsp      github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:213 +0x1ad
2023-05-12T22:11:06.169Z ring-rtsp created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-05-12T22:11:06.169Z ring-rtsp      github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:72 +0x48
2023-05-12T22:11:06.200Z ring-wrtc [Front] Live stream WebRTC session has disconnected
```

The go2rtc server crashed, but didn't appear to fully exit, so ring-mqtt was unable to restart it.  Not sure what to do with this or why it crashed, but I see a lot of very long delays for some stream startups and potential network issues (based on both logs you sent me) or possibly resources being overloaded.  Even your fastest times are far slower than I would expect:
```
2023-05-12T19:55:10.074Z ring-rtsp [go2rtc] DBG [exec] run launch=6.912029604s
2023-05-12T19:56:25.180Z ring-rtsp [go2rtc] DBG [exec] run launch=4.323539812s
2023-05-12T19:57:41.905Z ring-rtsp [go2rtc] DBG [exec] run launch=4.353017651s
2023-05-12T20:01:38.551Z ring-rtsp [go2rtc] DBG [exec] run launch=4.682942894s
2023-05-12T20:11:50.863Z ring-rtsp [go2rtc] DBG [exec] run launch=4.936128684s
2023-05-12T20:12:05.397Z ring-rtsp [go2rtc] DBG [exec] run launch=4.333947625s
2023-05-12T20:24:28.471Z ring-rtsp [go2rtc] DBG [exec] run launch=4.213281904s
2023-05-12T20:32:49.321Z ring-rtsp [go2rtc] DBG [exec] run launch=4.326448271s
2023-05-12T20:40:59.810Z ring-rtsp [go2rtc] DBG [exec] run launch=8.410263458s
2023-05-12T20:41:24.485Z ring-rtsp [go2rtc] DBG [exec] run launch=4.34742133s
2023-05-12T20:50:29.096Z ring-rtsp [go2rtc] DBG [exec] run launch=16.323243424s
2023-05-12T20:51:00.890Z ring-rtsp [go2rtc] DBG [exec] run launch=22.994095385s
2023-05-12T20:58:22.943Z ring-rtsp [go2rtc] DBG [exec] run launch=4.452412846s
2023-05-12T22:11:06.161Z ring-rtsp [go2rtc] DBG [exec] run launch=4.593008134s
```

Anything over 5 seconds basically is a fail, so it's barely working in any case.

**Comment by shimmers1** [comment]
Thanks for that Tom.

I got in touch with Alex (developer of go2rtc) and asked him about these
errors and he said that it must be because we are using an older
version/build of go2rtc.

Can you confirm whether that is a possibility?

**Comment by tsightler** [comment]
I had already contacted go2rtc project about it and he believes that specific crash is fixed.  The dev branch already has the latest go2rtc, so it might be addressed there.  That being said, I still believe your bigger issue is networking related, I'm not sure you will ever see reliable operation with these issues.

**Comment by shimmers1** [comment]
Is there any way to determine exactly what is causing the issues? Is it CPU or networking ?

**Comment by tsightler** [comment]
My gut says networking just because the logs you sent me from HA showed a second camera that appeared to disconnect at the same time with an error.  But it's solely just a guess and, unfortunately, I don't have time to help people troubleshoot environment specific issues, but just to give you some idea, while your cameras are taking >4 seconds to launch the stream pretty much every single time, my cameras regularly launch a stream in <2 seconds, and almost never more than 3 seconds.

Note that this could also be the networking for the camera, I've seen the especially common with doorbells used in neighborhoods where Wifi speeds are pretty poor overall.  The WebRTC in the Ring app handles these poor connections pretty well, but RTSP is a lot more sensitive since it was primary designed for local streaming.    Maybe someday someone will actually care about the native Ring HA addon and just implement WebRTC streaming directly in it.

For now I'm going to close this.  You can test the dev branch if you like but regardless, the next version of ring-mqtt will include the latest go2rtc version so perhaps the crash itself will be fixed.  Thanks for the report on that.

**Comment by shimmers1** [comment]
Thanks for all your help.

I disabled the second camera and it looks like the Ring is working now!

Just 2 more questions:

1. Is there any way to change the frequency of still images displayed?
2. Is there a way to create an automation based on motion from my ring
camera, I wasn't sure what the trigger would be

Thanks again

**Comment by tsightler** [comment]
Snapshot interval is configurable and you can see the settings directly in the HA UI (labeled "Snapshot Interval") and is also covered in documentation.  Automation based on motion is generic HA question, of course it is possible to use motion sensor as trigger.
