### ISSUE TITLE
5.6.1  - Bridge addition breaking new version

### ISSUE THREAD

**Issue by j6s33m** [tsightler/ring-mqtt#724]
Looks like the new bridge addition is causing an error with load. 

ring-mqtt.js version: 5.6.1
Node version v18.17.1
NPM version 9.1.2
git version 2.38.5

2023-09-03T18:18:32.178Z ring-mqtt WARNING - Unhandled Promise Rejection
2023-09-03T18:18:32.180Z ring-mqtt Class constructor Bridge cannot be invoked without 'new'
2023-09-03T18:18:32.181Z ring-mqtt TypeError: Class constructor Bridge cannot be invoked without 'new'
    at RingMqtt.getDevice (file:///app/ring-mqtt-latest/lib/ring.js:352:69)
    at RingMqtt.initRingData (file:///app/ring-mqtt-latest/lib/ring.js:238:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EventEmitter.<anonymous> (file:///app/ring-mqtt-latest/lib/ring.js:49:21)

**Comment by j6s33m** [comment]
5.6.2 fixed the issue. Thanks
