### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by bucks7756** [tsightler/ring-mqtt#75]
I'm at a loss.  I get that my ring token is invalid every time I try to install.  The ring token comes in every time, and is always different.  I simply copy and paste it into the docker script and get an error.  Any help would be amazing!  Thanks.

Successfully logged in to Ring. Please add the following to your config:

2020-07-07T20:57:40.700Z ring-mqtt Configuration file read from: ./config
2020-07-07T20:57:40.701Z ring-mqtt Configuration file not found, try environment variables!
2020-07-07T20:57:40.919Z ring-mqtt Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData (/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/ring-mqtt/node_modules/ring-client-api/lib/api/rest-client.js:88:16)

Script I run:
docker run --rm -e "MQTTHOST={192.168.1.50}" -e "MQTTPORT={1883}" -e "MQTTRINGTOPIC={ring}" -e "MQTTHASSTOPIC={hass/status}" -e "MQTTUSER={mosquitto}" -e "MQTTPASSWORD={...}" -e "RINGTOKEN={...}" -e "ENABLECAMERAS={true}" -e "RINGLOCATIONIDS={...}" -e "DEBUG=ring-mqtt" tsightler/ring-mqtt

**Comment by tsightler** [comment]
You shouldn't be including the brackets {} in the actual command line values, the brackets are there in the documentation to show as placeholders for the actual values.

**Comment by bucks7756** [comment]
You are awesome.  Thanks so much.  I feel like the older version let me do it with the brackets but all is good now!
