### ISSUE TITLE
Ring Motion Sensors have gone Offline

### ISSUE THREAD

**Issue by TonyMontuna** [tsightler/ring-mqtt#814]
### Describe the Bug

Roughly 8 hours before this post, all ring motion sensors have gone offline

Home Assistant is encountering an HTTP 500 (Internal Server Error) when attempting to communicate with the Ring service. This error suggests an issue on the server side of the Ring service that the add-on is trying to access. Specifically, the error occurs when the add-on makes HTTP requests to the Ring server, and the server responds with an error status, indicating a problem with the Ring server itself or with the interaction between the add-on and the server.

Several key points stand out from the logs:

Repeated HTTP 500 Errors: The add-on consistently receives HTTP 500 errors over multiple attempts to communicate with the Ring service, indicating a persistent issue.
Unhandled Promise Rejections: These warnings suggest that the code is not properly handling errors that occur during asynchronous operations. While this might not be the cause of the communication errors, it indicates potential areas for improvement in the add-on's error handling.
Impact on Functionality: Given that these errors occur when attempting to retrieve updated motion snapshots, it's likely that the add-on is unable to complete its intended operations, such as updating device states or fetching new event data, leading to your Ring devices appearing offline in Home Assistant.

### Steps to Reproduce

No steps needed, they just went offline

### Expected Behavior

They should be online, communicating with MQTT

### Log Output

```shell
at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:31:39.073Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:31:39.073Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:31:39.073Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:31:59.076Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:31:59.076Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:31:59.077Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:31:59.077Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:31:59.077Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:31:59.077Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:31:59.077Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:31:59.077Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:31:59.077Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:19.076Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:19.076Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:19.076Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:19.077Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:19.078Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:19.078Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:19.078Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:19.078Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:19.078Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:39.077Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:39.077Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:39.077Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:39.077Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:39.077Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:39.077Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:39.078Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:39.078Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:39.078Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:55.159Z ring-mqtt [Rutherford Garage] All motion dings for camera have expired
2024-03-28T15:32:55.159Z ring-mqtt [Rutherford Garage] ring/dr721x-3erub-0/camera/2c6b7d0aa11f/motion/state OFF
2024-03-28T15:32:55.159Z ring-attr [Rutherford Garage] ring/dr721x-3erub-0/camera/2c6b7d0aa11f/motion/attributes {"lastMotion":1711639794,"lastMotionTime":"2024-03-28T15:29:54Z","personDetected":false,"motionDetectionEnabled":true}
2024-03-28T15:32:59.078Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:59.078Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:59.078Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:59.078Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:59.078Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:59.078Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:32:59.078Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:32:59.078Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:32:59.078Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:33:19.079Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:33:19.079Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:33:19.079Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:33:19.079Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:33:19.079Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:33:19.079Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:33:19.080Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:33:19.080Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:33:19.080Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:33:39.079Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:33:39.079Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:33:39.079Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:33:39.080Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:33:39.080Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:33:39.080Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-28T15:33:39.080Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-03-28T15:33:39.080Z ring-mqtt Response code 500 (Internal Server Error)
2024-03-28T15:33:39.080Z ring-mqtt HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Config File

```shell
mqtt_url: mqtt://auto_username:auto_password@auto_hostname
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: "XXXXX"
enable_cameras: true
enable_modes: true
enable_panic: true
branch: addon
debug: ring-*
location_ids: []
```

### Install Type

Home Assistant Add On

### Version

5.6.3

### Operating System

Home Assistant OS

### Architecture

arm64

### Machine Details

Dell Optiplex

**Comment by tsightler** [comment]
This does not appear to be a bug, please following the troubleshooting steps:

https://github.com/tsightler/ring-mqtt/wiki/Support-&-Troubleshooting#troubleshooting
