### ISSUE TITLE
Websocket ticket requests fail with 500 server error

### ISSUE THREAD

**Issue by yieldhog** [tsightler/ring-mqtt#861]
### Describe the Bug

No longer able to connect to ring

### Steps to Reproduce

Reloaded add-on

### Expected Behavior

NA

### Log Output

```shell
2024-06-18T16:54:04.643Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-06-18T16:54:04.643Z ring-mqtt Response code 500 (Server Error)
2024-06-18T16:54:04.643Z ring-mqtt HTTPError: Response code 500 (Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Config File

```shell
Na
```

### Install Type

Home assistant add-on

### Version

5.6.6

### Operating System

Home assistant OS

### Architecture

Na

### Machine Details

Intel nuc

**Comment by clowncracker** [comment]
I'm running into the same issue, I ran through all of the troubleshooting steps outlined here:

https://github.com/tsightler/ring-mqtt/wiki/Support-&-Troubleshooting#troubleshooting

**Comment by zarzycki** [comment]
Same. Also forced a new authentication via the UI which succeeded, but the problem persists.

**Comment by TheLinuxTrucker** [comment]
Just wanted to add that I am having the same issue starting a couple of hours ago. Ran through the usual steps to fix and nothing seems to help. I’m using the separate docker container, updated today after problems started. So it isn’t just the add-on. Maybe Ring is having some issues today?

**Comment by calisro** [comment]
Please THUMBS up the original thread if you have hte same issue rather than adding "me too" comments.

**Comment by t-flow-sash** [comment]
Same but in a dedicated container. All of a sudden the 500 is thrown even after full rebuild

**Comment by philhendren** [comment]
So glad I found this thread via Reddit. It died a couple of hours ago.

**Comment by janprive** [comment]
Trying to control Ring over the home-assistant scrypted-addon doesn't work either.

**Comment by Tramatnois** [comment]
me too

**Comment by Alniro77** [comment]
exactement la même issue pour moi :

Running ring-mqtt...
2024-06-18T19:07:26.127Z ring-mqtt Detected runmode: addon
2024-06-18T19:07:26.129Z ring-mqtt Configuration file: /data/options.json
2024-06-18T19:07:29.875Z ring-mqtt Reading latest data from state file: /data/ring-state.json
2024-06-18T19:07:29.880Z ring-mqtt Succesfully started the token generator web UI
2024-06-18T19:07:29.894Z ring-mqtt Discovered MQTT Host: core-mosquitto
2024-06-18T19:07:29.895Z ring-mqtt Discovered MQTT Port: 1883
2024-06-18T19:07:29.896Z ring-mqtt Discovered MQTT User: addons
2024-06-18T19:07:29.897Z ring-mqtt Discovered MQTT password: <hidden>
2024-06-18T19:07:29.897Z ring-mqtt MQTT URL: mqtt://addons:********@core-mosquitto:1883
2024-06-18T19:07:29.970Z ring-mqtt Attempting connection to Ring API using saved refresh token...
2024-06-18T19:07:32.684Z ring-mqtt Successfully established connection to Ring API using saved token
2024-06-18T19:07:32.685Z ring-mqtt Received updated refresh token
2024-06-18T19:07:32.686Z ring-mqtt Saving updated refresh token to state file
2024-06-18T19:07:33.710Z ring-mqtt Successfully saved updated state file: /data/ring-state.json
2024-06-18T19:07:34.686Z ring-mqtt Attempting connection to MQTT broker...
2024-06-18T19:07:35.166Z ring-mqtt MQTT connection established, processing Ring locations...
2024-06-18T19:07:37.587Z ring-mqtt Home Assistant state topic homeassistant/status received message: offline
2024-06-18T19:07:37.829Z ring-mqtt ------------------------------------------------------------------------------------------
2024-06-18T19:07:37.830Z ring-mqtt This account has access to the following locations:
2024-06-18T19:07:37.830Z ring-mqtt            Mormant (0a714d5a-31eb-424d-bdf6-8998bddbdd6e)
2024-06-18T19:07:37.830Z ring-mqtt                                                                                           
2024-06-18T19:07:37.831Z ring-mqtt IMPORTANT: If *ANY* alarm or smart lighting hubs at these locations are *OFFLINE* 
2024-06-18T19:07:37.831Z ring-mqtt            the device discovery process below will hang and no devices will be    
2024-06-18T19:07:37.831Z ring-mqtt            published!                                                             
2024-06-18T19:07:37.831Z ring-mqtt                                                                                           
2024-06-18T19:07:37.831Z ring-mqtt            If the message "Device Discovery Complete!" is not logged below, please
2024-06-18T19:07:37.831Z ring-mqtt            carefully check the Ring app for any hubs or smart lighting devices    
2024-06-18T19:07:37.831Z ring-mqtt            that are in offline state and either remove them from the location or  
2024-06-18T19:07:37.831Z ring-mqtt            bring them back online prior to restarting ring-mqtt.                  
2024-06-18T19:07:37.831Z ring-mqtt                                                                                           
2024-06-18T19:07:37.831Z ring-mqtt            If desired, the "location_ids" config option can be used to restrict   
2024-06-18T19:07:37.831Z ring-mqtt            discovery to specific locations. See the documentation for details.    
2024-06-18T19:07:37.831Z ring-mqtt ------------------------------------------------------------------------------------------
2024-06-18T19:07:37.832Z ring-mqtt Starting Device Discovery...
2024-06-18T19:07:37.832Z ring-mqtt                                                                                           
2024-06-18T19:07:37.832Z ring-mqtt New location: Mormant (0a714d5a-31eb-424d-bdf6-8998bddbdd6e)
2024-06-18T19:07:38.324Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-06-18T19:07:38.324Z ring-mqtt Response code 500 (Server Error)
2024-06-18T19:07:38.324Z ring-mqtt HTTPError: Response code 500 (Server Error)
    at Request.<anonymous> (/app/ring-mqtt/node_modules/ring-client-api/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by tsightler** [comment]
Please read my comments here:

https://github.com/dgreif/ring/issues/1431#issuecomment-2176795990

As this is an issue coming from ring-client-api due to either a temporary outage or permanent change of the Ring server infrastructure, there is nothing that can be done with it here.  I will continue to research and try to resolve it in ring-client-api.  If anyone has unlimited time to go digging, feel free to use the information there to submit a PR.

**Comment by WhyAydan** [comment]
Well this isn't looking good! Looks like it might be soon time to scrap the Ring Alarm.

**Comment by Jonesnetwork** [comment]
Digging deeper the error relates to the volume on the base station. (Something causing the error on the api on the back end)

quick fix
Open ring ring
Go to devices
Select base station
Audio setting
Move volume to lowest
Save
Move volume back
Save
Restart add on

the above fixed mine 👍

**Comment by jianyu-li** [comment]
> Digging deeper the error relates to the volume on the base station. (Something causing the error on the api on the back end)
> 
> quick fix Open ring app on your phone Go to devices Select base station Audio setting Move volume to lowest Save Move volume back Save Restart add on in home assistant Test (should now be working 😎)
> 
> the above fixed mine 👍

Oddly enough this worked for me too

**Comment by tsightler** [comment]
> Digging deeper the error relates to the volume on the base station. (Something causing the error on the api on the back end)

This is just coincidence, it has nothing to do with the volume, as a matter of fact, it happens before any devices are even initialized.  It seems Ring has corrected their service issue.

**Comment by sofapi** [comment]
I’m still not able to get past the 500 error after multiple reboots/reloads etc.  Any advice or is it a case of just waiting to see what happens now.

**Comment by tsightler** [comment]
> I’m still not able to get past the 500 error after multiple reboots/reloads etc. Any advice or is it a case of just waiting to see what happens now.

It seems to be up and down, I'm also getting the error again. It had some period of up and down this morning as well. At this point, if you don't know how to manually change the URL as mentioned in the linked ring-client-api thread, then best bet is just to wait. Either it will stabilize, or we'll push out an update that uses the new URL.

**Comment by Vib1240n** [comment]
> > Digging deeper the error relates to the volume on the base station. (Something causing the error on the api on the back end)
> 
> This is just coincidence, it has nothing to do with the volume, as a matter of fact, it happens before any devices are even initialized. It seems Ring has corrected their service issue.

Not sure if it is a coincidence, although it does logically seem like a coincidence but turning down the base station volume did enable find all the devices in the integration. I had restarted multiple times, and rechecked all the settings as well as deleted and reinstalled the integration.

**Comment by coryb155** [comment]
> Digging deeper the error relates to the volume on the base station. (Something causing the error on the api on the back end)
> 
> quick fix Open ring app on your phone Go to devices Select base station Audio setting Move volume to lowest Save Move volume back Save Restart add on in home assistant Test (should now be working 😎)
> 
> the above fixed mine 👍

Same. So weird.

**Comment by tsightler** [comment]
ring-mqtt v5.6.7 has been released with a fix for this issue.

**Comment by codemannh** [comment]
Wow! This worked for me as well. I have not upgraded the docker container yet, but it’s now working. Appreciate the info.

Bill

________________________________
