### ISSUE TITLE
Acquire Refresh Token is not working after I hit Submit

### ISSUE THREAD

**Issue by akdellm01** [tsightler/ring-mqtt#938]
### Is there an existing issue for this?

- [X] I have searched all existing open/closed issues

### Is this really a bug or just a usage/support question?

- [X] I'm confident this is a bug.

### Have you read and followed any recommendations in the Support and Troubleshooting section of the wiki?

- [X] I have read the support wiki and followed any applicable steps.

### Did this issue start after an upgrade?

- [X] This not an upgrade issue or I have read the release notes and performed any applicable steps that match my issue.

### Are you prepared to respond and provide all relevant information (logs, screenshots, etc)

- [X] I am prepared to provide logs, answer questions, and respond in a reasonable timeframe.

### Describe the Bug

On my Home Assistant Green device I have successfully installed Ring MQQT with the Video Streaming add-on utilizing the provided GitHub link. Additionally, I have installed the MQQT Broker. However, during the final step, when I access the Open Web UI and input my Ring credentials prior to clicking the submit button, no action occurs.

### Steps to Reproduce

During the final step, when I access the Open Web UI and input my Ring credentials prior to clicking the submit button, no action occurs.

### Expected Behavior

Expected behaviour is that the system should pass the 2FA and authenticate my ring account with HA

### Log Output

```shell
-------------------------------------------------------
ring-mqtt.js version: 5.7.2
Node version v22.11.0
NPM version 10.9.0
git version 2.45.2
-------------------------------------------------------
Running ring-mqtt...
2024-11-22T22:37:02.452Z ring-mqtt Detected runmode: addon
2024-11-22T22:37:02.460Z ring-mqtt Configuration file: /data/options.json
2024-11-22T22:37:07.545Z ring-mqtt State file /data/ring-state.json not found. No saved state data available.
2024-11-22T22:37:07.546Z ring-mqtt No refresh token was found in state file, generate a token using the addon Web UI
2024-11-22T22:37:07.567Z ring-mqtt Succesfully started the token generator web UI
2024-11-22T22:37:07.582Z ring-mqtt Configured MQTT Host: core-mosquitto
2024-11-22T22:37:07.583Z ring-mqtt Discovered MQTT Port: 1883
2024-11-22T22:37:07.585Z ring-mqtt Configured MQTT User: akshay
2024-11-22T22:37:07.587Z ring-mqtt Configured MQTT password: <hidden>
2024-11-22T22:37:07.591Z ring-mqtt MQTT URL: mqtt://akshay:********@core-mosquitto:1883
2024-11-22T22:44:06.333Z ring-mqtt Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>
2024-11-22T22:44:06.341Z ring-mqtt WARNING - Unhandled Promise Rejection
2024-11-22T22:44:06.341Z ring-mqtt argument val is invalid
2024-11-22T22:44:06.342Z ring-mqtt TypeError: argument val is invalid
    at Object.serialize (/app/ring-mqtt/node_modules/cookie/index.js:198:11)
    at res.cookie (/app/ring-mqtt/node_modules/express/lib/response.js:892:36)
    at file:///app/ring-mqtt/lib/tokenapp.js:91:25
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-11-22T22:56:00.308Z ring-mqtt Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

### Config File

```shell
mqtt://[Username]:[Password]@core-mosquitto
```

### Install Type

Home Assistant Addon

### Version

v5.7.2

### Operating System

Home Assistant OS

### Architecture

arm64

### Machine Details

Home Assistant Green

**Comment by tsightler** [comment]
406 generally means Ring servers are blocking your IP address.  Are you using any VPN or other service like that?  Sometimes Ring's auth servers are just offline for a while.  For temporary blocks, it usually clears in a few hours, however, most VPNs are permanently blocked by Ring.
